version: "3"

volumes:
  advisor_local_postgres_data: {}
  advisor_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: advisor_local_django
    container_name: advisor_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./apps:/project/apps:z
      - ./config:/project/config:z
      - ./locale:/project/locale:z
      - ./tests:/project/tests:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: advisor_production_postgres
    container_name: advisor_local_postgres
    volumes:
      - advisor_local_postgres_data:/var/lib/postgresql/data
      - advisor_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: advisor_local_docs
    container_name: advisor_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/project/config:z
      - ./apps:/project/apps:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: advisor_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: advisor_local_redis

  celeryworker:
    <<: *django
    image: advisor_local_celeryworker
    container_name: advisor_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: advisor_local_celerybeat
    container_name: advisor_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat
