# Generated by Django 4.2.11 on 2024-04-06 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('uri', models.URLField(blank=True, help_text='Could be a ORCID link, a resume on Lattes etc.', verbose_name="Source of the author's information")),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='The slug of the keyword', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, help_text='The ISO 3166-1 alfa-3 code of the country', max_length=3)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('published', models.DateField(null=True)),
                ('uri', models.URLField(blank=True, help_text='Link to the paper in its source website', verbose_name='Link to the paper')),
                ('doi', models.CharField(blank=True, help_text='The DOI (Digital Object Identifier) of the paper', max_length=255, unique=True, verbose_name='DOI')),
                ('pdf', models.URLField(blank=True, help_text='Link to the PDF of the paper', verbose_name='Link to the PDF')),
                ('authors', models.ManyToManyField(related_name='papers', to='papers.author')),
                ('keywords', models.ManyToManyField(related_name='papers', to='papers.keyword')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='papers.location')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country'], name='country_index'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city', 'country', 'state'], name='location_index'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['name'], name='keyword_name_index'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['uuid'], name='papers_auth_uuid_31fa29_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='author_name_index'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['uuid'], name='papers_pape_uuid_e86603_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['title', 'abstract'], name='search_index'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['-published'], name='published_index'),
        ),
    ]
