# Generated by Django 4.2.11 on 2024-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reviews_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='reviews_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
