# Generated by Django 4.2.11 on 2024-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_reviews_count_paper_reviews_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reviews_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
