# Generated by Django 4.2.11 on 2024-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_reviews_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='reviews_last_updated',
        ),
        migrations.AddField(
            model_name='paper',
            name='index',
            field=models.BigIntegerField(blank=True, help_text='Position index for embeddings', null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='last_reviews_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
