# Generated by Django 4.2.11 on 2024-04-09 00:12

import uuid

import django.core.serializers.json
import django_extensions.db.fields
from django.db import migrations, models

import apps.ml.encoders
import apps.ml.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.ml.models.base.model_file_handler)),
                ('latest', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('svd', 'SVD')], max_length=3)),
                ('params', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Parameters for training', null=True)),
                ('validation_results', models.JSONField(encoder=apps.ml.encoders.ValidationResultsJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SVDModel',
            fields=[
            ],
            options={
                'verbose_name': 'SVD Model',
                'verbose_name_plural': 'SVD Models',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ml.model',),
        ),
    ]
