# Generated by Django 4.2.11 on 2024-04-12 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
